### ISSUE TITLE
TOdo

### ISSUE THREAD

**Issue by 5tarlight** [5tarlight/aster#1]
# Login
# Sign Up

/game 라우터에서 세션 확인
로그인페이지로 이동 로그인 페이지는 회원가입페이지로 이동버튼을 가지고 있음
세션확인되면 로그인 페이지로 이동

**Comment by 5tarlight** [comment]
session check done

**Comment by 5tarlight** [comment]
login page design remaining

**Comment by 5tarlight** [comment]
login page done

**Comment by 5tarlight** [comment]
sign up page and router

**Comment by 5tarlight** [comment]
Annnnnnnnnnd post request and DB query remaining

**Comment by ttakkku** [comment]
hmm..

**Comment by godmoonl** [comment]
🤔

**Comment by ttakkku** [comment]
Groot say "I am Groot"

**Comment by 5tarlight** [comment]
@takkku your not groot

**Comment by 5tarlight** [comment]
@godmoonl thinking

**Comment by ttakkku** [comment]
No

**Comment by godmoonl** [comment]
I'm thinking...

**Comment by 5tarlight** [comment]
자 다시 개발합시다
